name: Update MSRV

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  UpdateMSRV:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Install cargo-msrv
        run: cargo install cargo-msrv --locked

      - name: Find msrv
        run: echo "MSRV=$(cargo msrv find --output-format minimal)" >> $GITHUB_ENV

      - name: Set msrv
        run: cargo msrv set ${{ env.MSRV }}

      - name: Update
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add Cargo.toml
          git commit -m "Set MSRV into ${{ env.MSRV }}" || true
          git push
